# Generated by Django 4.0.5 on 2022-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='step',
            field=models.CharField(max_length=2),
        ),
    ]
